"""Streamlit Web UI for Real-Time Fraud Scoring Service (Stage 13).

Provides interactive scoring, sample preset transactions, SHAP reason visualizations,
batch evaluation, and system metadata.
"""

import json
import os
import time

import matplotlib.pyplot as plt
import pandas as pd
import requests
import streamlit as st

# Page Configuration
st.set_page_config(
    page_title="FraudShield AI - Real-Time Fraud Detection",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Custom Styling
st.markdown(
    """
    <style>
    .main-header {
        font-size: 2.3rem;
        font-weight: 700;
        background: linear-gradient(90deg, #1E88E5 0%, #7B1FA2 100%);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        margin-bottom: 0rem;
    }
    .sub-header {
        font-size: 1.0rem;
        color: #78909C;
        margin-bottom: 1.5rem;
    }
    .badge-approve {
        background-color: #2E7D32;
        color: white;
        padding: 6px 16px;
        border-radius: 20px;
        font-weight: bold;
        font-size: 1.2rem;
        display: inline-block;
    }
    .badge-review {
        background-color: #F57F17;
        color: white;
        padding: 6px 16px;
        border-radius: 20px;
        font-weight: bold;
        font-size: 1.2rem;
        display: inline-block;
    }
    .badge-block {
        background-color: #C62828;
        color: white;
        padding: 6px 16px;
        border-radius: 20px;
        font-weight: bold;
        font-size: 1.2rem;
        display: inline-block;
    }
    .demo-notice {
        background-color: #0D47A115;
        border-left: 4px solid #1E88E5;
        padding: 10px 15px;
        border-radius: 4px;
        font-size: 0.9rem;
        margin-bottom: 1rem;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

# Backend API Configuration
DEFAULT_API_URL = os.getenv("API_URL", "http://localhost:8000")
DEFAULT_API_KEY = os.getenv("API_KEY", "demo-api-key-12345")

st.sidebar.title("🛡️ FraudShield Control")
api_url = st.sidebar.text_input("Backend API Base URL", value=DEFAULT_API_URL)
api_key = st.sidebar.text_input("API Key", value=DEFAULT_API_KEY, type="password")

# Check API Health
headers = {"X-API-Key": api_key, "Content-Type": "application/json"}
api_healthy = False
try:
    resp = requests.get(f"{api_url}/health", timeout=3)
    if resp.status_code == 200:
        api_healthy = True
        st.sidebar.success("Backend API: Connected (200 OK)")
    else:
        st.sidebar.warning(f"Backend API status: {resp.status_code}")
except Exception:
    st.sidebar.error("Backend API: Offline / Unreachable")

st.markdown('<div class="main-header">Real-Time Fraud Scoring Dashboard</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-header">Production-grade IEEE-CIS ML Scoring Engine with SHAP Per-Prediction Reasons</div>', unsafe_allow_html=True)

st.markdown(
    '<div class="demo-notice">⚠️ <b>DEMO ONLY NOTICE:</b> Predictions are generated by LightGBM model calibrated on time-split validation data. Do not use for actual financial authorization.</div>',
    unsafe_allow_html=True,
)

# Tabs
tab1, tab2, tab3 = st.tabs(["⚡ Single Transaction Scoring", "📦 Batch Scoring", "📊 Model Info & System Status"])

# Presets
PRESETS = {
    "Low-Risk Card Purchase": {
        "transaction_id": "tx_preset_low_risk",
        "TransactionDT": 86400,
        "TransactionAmt": 34.50,
        "ProductCD": "W",
        "card1": 1000,
        "card2": 555.0,
        "card3": 150.0,
        "card4": "visa",
        "card5": 226.0,
        "card6": "debit",
        "addr1": 315.0,
        "addr2": 87.0,
        "P_emaildomain": "gmail.com",
        "R_emaildomain": "gmail.com",
        "DeviceType": "desktop",
        "DeviceInfo": "Windows",
    },
    "High-Risk Crypto/Cross-Border": {
        "transaction_id": "tx_preset_high_risk",
        "TransactionDT": 90000,
        "TransactionAmt": 1850.00,
        "ProductCD": "C",
        "card1": 19800,
        "card2": 100.0,
        "card3": 185.0,
        "card4": "mastercard",
        "card5": 102.0,
        "card6": "credit",
        "addr1": 500.0,
        "addr2": 87.0,
        "P_emaildomain": "anonymous.com",
        "R_emaildomain": "yahoo.com",
        "DeviceType": "mobile",
        "DeviceInfo": "iOS Device",
    },
    "Medium-Risk Manual Review": {
        "transaction_id": "tx_preset_review",
        "TransactionDT": 88000,
        "TransactionAmt": 320.00,
        "ProductCD": "H",
        "card1": 7500,
        "card2": 321.0,
        "card3": 150.0,
        "card4": "visa",
        "card5": 226.0,
        "card6": "credit",
        "addr1": 126.0,
        "addr2": 87.0,
        "P_emaildomain": "hotmail.com",
        "R_emaildomain": "hotmail.com",
        "DeviceType": "desktop",
        "DeviceInfo": "MacOS",
    },
}

with tab1:
    col_preset, col_empty = st.columns([2, 2])
    with col_preset:
        selected_preset = st.selectbox("Load Sample Preset Transaction:", ["Custom Entry"] + list(PRESETS.keys()))

    preset_data = PRESETS.get(selected_preset, PRESETS["Low-Risk Card Purchase"])

    with st.form("single_tx_form"):
        col1, col2, col3 = st.columns(3)
        with col1:
            tx_id = st.text_input("Transaction ID", value=preset_data.get("transaction_id", "tx_demo_001"))
            tx_dt = st.number_input("Transaction DT (seconds)", value=int(preset_data.get("TransactionDT", 86400)))
            tx_amt = st.number_input("Transaction Amount ($)", value=float(preset_data.get("TransactionAmt", 100.0)), min_value=0.01)
            prod_cd = st.selectbox("Product Code (ProductCD)", ["W", "C", "R", "H", "S"], index=["W", "C", "R", "H", "S"].index(preset_data.get("ProductCD", "W")))

        with col2:
            card1 = st.number_input("Card 1 (Issuer)", value=int(preset_data.get("card1", 1000)))
            card2 = st.number_input("Card 2", value=float(preset_data.get("card2", 500.0)))
            card4 = st.selectbox("Card Brand (card4)", ["visa", "mastercard", "discover", "american express"], index=0)
            card6 = st.selectbox("Card Type (card6)", ["debit", "credit"], index=0)

        with col3:
            p_email = st.text_input("Purchaser Email Domain", value=preset_data.get("P_emaildomain", "gmail.com"))
            r_email = st.text_input("Recipient Email Domain", value=preset_data.get("R_emaildomain", "gmail.com"))
            dev_type = st.selectbox("Device Type", ["desktop", "mobile"], index=0)
            dev_info = st.text_input("Device Info", value=preset_data.get("DeviceInfo", "Windows"))

        explain_toggle = st.checkbox("Return SHAP Feature Reasons", value=True)
        submit_btn = st.form_submit_button("🛡️ Score Transaction Now", use_container_width=True)

    if submit_btn:
        payload = {
            "transaction_id": tx_id,
            "TransactionDT": tx_dt,
            "TransactionAmt": tx_amt,
            "ProductCD": prod_cd,
            "card1": card1,
            "card2": card2,
            "card4": card4,
            "card6": card6,
            "P_emaildomain": p_email,
            "R_emaildomain": r_email,
            "DeviceType": dev_type,
            "DeviceInfo": dev_info,
        }

        try:
            t0 = time.time()
            score_url = f"{api_url}/v1/score?explain={str(explain_toggle).lower()}"
            res = requests.post(score_url, headers=headers, json=payload, timeout=10)
            elapsed_ms = round((time.time() - t0) * 1000, 2)

            if res.status_code == 200:
                data = res.json()
                prob = data["fraud_probability"]
                decision = data["decision"]
                risk_band = data["risk_band"]
                reasons = data.get("reasons", [])

                st.markdown("---")
                st.subheader("🎯 Scoring Results")

                res_col1, res_col2, res_col3, res_col4 = st.columns(4)
                with res_col1:
                    st.metric("Calibrated Fraud Probability", f"{prob:.4f} ({prob*100:.2f}%)")
                with res_col2:
                    if decision == "approve":
                        st.markdown('Decision: <div class="badge-approve">APPROVE</div>', unsafe_allow_html=True)
                    elif decision == "review":
                        st.markdown('Decision: <div class="badge-review">MANUAL REVIEW</div>', unsafe_allow_html=True)
                    else:
                        st.markdown('Decision: <div class="badge-block">BLOCK</div>', unsafe_allow_html=True)
                with res_col3:
                    st.metric("Risk Band", risk_band)
                with res_col4:
                    st.metric("API Latency", f"{elapsed_ms} ms")

                st.progress(prob)

                # Reasons Visualization
                if reasons:
                    st.subheader("🔍 Top 5 Per-Prediction Reason Codes (SHAP Contributions)")
                    rdf = pd.DataFrame(reasons)

                    fig, ax = plt.subplots(figsize=(8, 3.5))
                    colors = ["#E53935" if d == "increases_risk" else "#43A047" for d in rdf["direction"]]
                    bars = ax.barh(rdf["label"], rdf["contribution"], color=colors)
                    ax.axvline(0, color="gray", linewidth=0.8, linestyle="--")
                    ax.set_xlabel("SHAP Contribution to Fraud Score")
                    ax.set_title("Feature Contribution Breakdown")
                    ax.invert_yaxis()
                    plt.tight_layout()
                    st.pyplot(fig)

                    st.dataframe(rdf[["label", "value", "contribution", "direction"]], use_container_width=True)

            else:
                st.error(f"API Error {res.status_code}: {res.text}")
        except Exception as err:
            st.error(f"Connection Error: Could not reach scoring API at {api_url}. Error: {err}")

with tab2:
    st.subheader("📦 Batch Transaction Scoring")
    st.write("Score up to 1,000 transactions simultaneously in high-throughput mode.")

    sample_batch = [PRESETS["Low-Risk Card Purchase"], PRESETS["High-Risk Crypto/Cross-Border"], PRESETS["Medium-Risk Manual Review"]]
    json_batch_input = st.text_area("JSON Batch Input:", value=json.dumps({"transactions": sample_batch}, indent=2), height=250)

    if st.button("🚀 Score Batch Transactions", use_container_width=True):
        try:
            batch_payload = json.loads(json_batch_input)
            res = requests.post(f"{api_url}/v1/score/batch?explain=false", headers=headers, json=batch_payload, timeout=15)
            if res.status_code == 200:
                bdata = res.json()
                st.success(f"Batch Processed {bdata['total_processed']} transactions in {bdata['batch_latency_ms']} ms")
                results_df = pd.DataFrame(bdata["results"])
                st.dataframe(results_df, use_container_width=True)
            else:
                st.error(f"Batch Error {res.status_code}: {res.text}")
        except Exception as e:
            st.error(f"Invalid JSON or Request Error: {e}")

with tab3:
    st.subheader("📊 Model Information & Threshold Configuration")
    try:
        minfo_res = requests.get(f"{api_url}/v1/model/info", headers=headers, timeout=5)
        if minfo_res.status_code == 200:
            minfo = minfo_res.json()
            st.json(minfo)
        else:
            st.warning("Model info endpoint returned non-200 status.")
    except Exception as e:
        st.error(f"Could not retrieve model info: {e}")
